import { IS_APPLE } from '@lexical/utils';

const EDITOR_SHORTCUTS = Object.freeze({
  ADD_COMMENT: IS_APPLE ? '⌘+Opt+M' : 'Ctrl+Alt+M',
  BOLD: IS_APPLE ? '⌘+B' : 'Ctrl+B',
  BULLET_LIST: IS_APPLE ? '⌘+Shift+8' : 'Ctrl+Shift+8',
  CAPITALIZE: IS_APPLE ? '⌃+Shift+3' : 'Ctrl+Shift+3',
  CENTER_ALIGN: IS_APPLE ? '⌘+Shift+E' : 'Ctrl+Shift+E',
  CHECK_LIST: IS_APPLE ? '⌘+Shift+9' : 'Ctrl+Shift+9',
  CLEAR_EDITOR: IS_APPLE ? '⌘+Opt+Backspace' : 'Ctrl+Alt+Backspace',
  CLEAR_FORMATTING: IS_APPLE ? '⌘+\\' : 'Ctrl+\\',
  CODE: IS_APPLE ? '⌘+Opt+C' : 'Ctrl+Alt+C',
  DECREASE_FONT_SIZE: IS_APPLE ? '⌘+Shift+,' : 'Ctrl+Shift+,',
  HEADING1: IS_APPLE ? '⌘+Opt+1' : 'Ctrl+Alt+1',
  HEADING2: IS_APPLE ? '⌘+Opt+2' : 'Ctrl+Alt+2',
  HEADING3: IS_APPLE ? '⌘+Opt+3' : 'Ctrl+Alt+3',
  HEADING4: IS_APPLE ? '⌘+Opt+4' : 'Ctrl+Alt+4',
  HEADING5: IS_APPLE ? '⌘+Opt+5' : 'Ctrl+Alt+5',
  HEADING6: IS_APPLE ? '⌘+Opt+6' : 'Ctrl+Alt+6',
  HIGHLIGHT: IS_APPLE ? '⌃+Shift+H' : 'Ctrl+Shift+H',
  INCREASE_FONT_SIZE: IS_APPLE ? '⌘+Shift+.' : 'Ctrl+Shift+.',
  INDENT: IS_APPLE ? '⌘+]' : 'Ctrl+]',
  INSERT_CODE_BLOCK: IS_APPLE ? '⌘+Shift+C' : 'Ctrl+Shift+C',
  INSERT_LINK: IS_APPLE ? '⌘+K' : 'Ctrl+K',
  ITALIC: IS_APPLE ? '⌘+I' : 'Ctrl+I',
  JUSTIFY_ALIGN: IS_APPLE ? '⌘+Shift+J' : 'Ctrl+Shift+J',
  LEFT_ALIGN: IS_APPLE ? '⌘+Shift+L' : 'Ctrl+Shift+L',
  LOWERCASE: IS_APPLE ? '⌃+Shift+1' : 'Ctrl+Shift+1',
  NORMAL: IS_APPLE ? '⌘+Opt+0' : 'Ctrl+Alt+0',
  NUMBERED_LIST: IS_APPLE ? '⌘+Shift+7' : 'Ctrl+Shift+7',
  OUTDENT: IS_APPLE ? '⌘+[' : 'Ctrl+[',
  QUOTE: IS_APPLE ? '⌃+Shift+Q' : 'Ctrl+Shift+Q',
  REDO: IS_APPLE ? '⌘+Shift+Z' : 'Ctrl+Y',
  RIGHT_ALIGN: IS_APPLE ? '⌘+Shift+R' : 'Ctrl+Shift+R',
  STRIKETHROUGH: IS_APPLE ? '⌘+Shift+X' : 'Ctrl+Shift+X',
  SUBSCRIPT: IS_APPLE ? '⌘+,' : 'Ctrl+,',
  SUPERSCRIPT: IS_APPLE ? '⌘+.' : 'Ctrl+.',
  UNDERLINE: IS_APPLE ? '⌘+U' : 'Ctrl+U',
  UNDO: IS_APPLE ? '⌘+Z' : 'Ctrl+Z',
  UPPERCASE: IS_APPLE ? '⌃+Shift+2' : 'Ctrl+Shift+2',
});

export default EDITOR_SHORTCUTS;
